const lessons = [
  {
    id: "1",
    title: "01. Introduction",
    progress: 0.78,
    lectures: "3",
    duration: "7 min",
    tutorials: [
      {
        id: "1",
        name: "Setting up individual Camera Rigs",
        duration: "00:44",
        isUnlocked: true,
      },
      {
        id: "2",
        name: "Setting Up VRTKs Tracked Alias",
        duration: "03:49",
        isUnlocked: true,
      },
      {
        id: "3",
        name: "Setting Up VRTKs Tracked Alias",
        duration: "05:25",
        isUnlocked: false,
      },
    ],
  },
  {
    id: "2",
    title: "02. Movement in VR",
    progress: 0.25,
    lectures: "3",
    duration: "7 min",
    tutorials: [
      {
        id: "1",
        name: "Setting up individual Camera Rigs",
        duration: "00:44",
        isUnlocked: true,
      },
      {
        id: "2",
        name: "Setting Up VRTKs Tracked Alias",
        duration: "03:49",
        isUnlocked: true,
      },
      {
        id: "3",
        name: "Setting Up VRTKs Tracked Alias",
        duration: "05:25",
        isUnlocked: false,
      },
    ],
  },
  {
    id: "3",
    title: "03. Distance Grabber",
    progress: 0.33,
    lectures: "3",
    duration: "7 min",
    tutorials: [
      {
        id: "1",
        name: "Setting up individual Camera Rigs",
        duration: "00:44",
        isUnlocked: true,
      },
      {
        id: "2",
        name: "Setting Up VRTKs Tracked Alias",
        duration: "03:49",
        isUnlocked: true,
      },
      {
        id: "3",
        name: "Setting Up VRTKs Tracked Alias",
        duration: "05:25",
        isUnlocked: false,
      },
    ],
  },
  {
    id: "4",
    title: "04. Snap Zones",
    progress: 0.1,
    lectures: "3",
    duration: "7 min",
    tutorials: [
      {
        id: "1",
        name: "Setting up individual Camera Rigs",
        duration: "00:44",
        isUnlocked: true,
      },
      {
        id: "2",
        name: "Setting Up VRTKs Tracked Alias",
        duration: "03:49",
        isUnlocked: true,
      },
      {
        id: "3",
        name: "Setting Up VRTKs Tracked Alias",
        duration: "05:25",
        isUnlocked: false,
      },
    ],
  },
];

const courses = [
  {
    id: "1",
    category: "Science",
    name: "Chapter 1 – Chemical Reactions and Equations.",
    author: "Jack Smith",
    thumbnail: { uri: "https://via.placeholder.com/270x270" },
    image: { uri: "https://via.placeholder.com/690x360" },
    icon: { uri: "https://via.placeholder.com/600x600" },
    preview_240x240: {
      uri: "https://via.placeholder.com/240x240",
    },
    preview_330x330: {
      uri: "https://via.placeholder.com/330x330",
    },
    preview_480x288: {
      uri: "https://via.placeholder.com/480x288",
    },
    preview_1005x495: {
      uri: "https://via.placeholder.com/1005x495",
    },
    location: "London Universiry",
    instructor: "Elizabeth Parker",
    instructorPhoto: { uri: "https://via.placeholder.com/273x273" },
    instructorRating: "4.5",
    instructorReviews: "116",
    instructorStudents: "936",
    instructorCourses: "12",
    position: "Professional Software Developer and Educator",
    aboutTeacher:
      "I started working as a software developer at the age of 23, and never looked back. I explored careers as varied as being a  Game Developer, Educator and Drone Pilot, over the last 25 years. None of these provided a continual challenge in the same way the combination of...",
    duration: "5h  30m",
    price: "35.00",
    oldPrice: "55.00",
    rating: "5.0",
    ratings: "149",
    topRated: true,
    popular: true,
    isNew: true,
    speciallyForYou: true,
    ongoing: false,
    completed: true,
    wishlist: true,
    lectures: "23",
    backgroundIcon: { uri: "https://via.placeholder.com/210x210" },
    backgroundColor: "#9BA0FC",
    lessons: lessons,
  },
  {
    id: "2",
    category: "Science",
    name: "Chapter 1 – Chemical Reactions and Equations.",
    author: "Jack Smith",
    thumbnail: { uri: "https://via.placeholder.com/270x270" },
    image: { uri: "https://via.placeholder.com/690x360" },
    icon: { uri: "https://via.placeholder.com/600x600" },
    preview_240x240: {
      uri: "https://via.placeholder.com/240x240",
    },
    preview_330x330: {
      uri: "https://via.placeholder.com/330x330",
    },
    preview_480x288: {
      uri: "https://via.placeholder.com/480x288",
    },
    preview_1005x495: {
      uri: "https://via.placeholder.com/1005x495",
    },
    location: "London Universiry",
    instructor: "Elizabeth Parker",
    instructorPhoto: { uri: "https://via.placeholder.com/273x273" },
    instructorRating: "4.5",
    instructorReviews: "116",
    instructorStudents: "936",
    instructorCourses: "12",
    position: "Professional Software Developer and Educator",
    aboutTeacher:
      "I started working as a software developer at the age of 23, and never looked back. I explored careers as varied as being a  Game Developer, Educator and Drone Pilot, over the last 25 years. None of these provided a continual challenge in the same way the combination of...",
    duration: "5h  30m",
    price: "35.00",
    oldPrice: "55.00",
    rating: "5.0",
    ratings: "149",
    topRated: false,
    popular: true,
    isNew: true,
    speciallyForYou: true,
    ongoing: false,
    completed: true,
    wishlist: true,
    lectures: "23",
    backgroundIcon: { uri: "https://via.placeholder.com/210x210" },
    backgroundColor: "#9BA0FC",
    lessons: lessons,
  },
  {
    id: "3",
    category: "Maths",
    name: "Chapter - 3: Pair of Linear Equations in Two Variables.",
    author: "Jack Smith",
    thumbnail: { uri: "https://via.placeholder.com/270x270" },
    image: { uri: "https://via.placeholder.com/690x360" },
    icon: { uri: "https://via.placeholder.com/600x600" },
    preview_240x240: {
      uri: "https://via.placeholder.com/240x240",
    },
    preview_330x330: {
      uri: "https://via.placeholder.com/330x330",
    },
    preview_480x288: {
      uri: "https://via.placeholder.com/480x288",
    },
    preview_1005x495: {
      uri: "https://via.placeholder.com/1005x495",
    },
    location: "London Universiry",
    instructor: "Elizabeth Parker",
    instructorPhoto: { uri: "https://via.placeholder.com/273x273" },
    instructorRating: "4.5",
    instructorReviews: "116",
    instructorStudents: "936",
    instructorCourses: "12",
    position: "Professional Software Developer and Educator",
    aboutTeacher:
      "I started working as a software developer at the age of 23, and never looked back. I explored careers as varied as being a  Game Developer, Educator and Drone Pilot, over the last 25 years. None of these provided a continual challenge in the same way the combination of...",
    duration: "5h  30m",
    price: "35.00",
    oldPrice: "55.00",
    oldPrice: "42.00",
    rating: "5.0",
    ratings: "149",
    topRated: true,
    popular: true,
    isNew: true,
    speciallyForYou: false,
    ongoing: false,
    completed: true,
    wishlist: true,
    lectures: "23",
    backgroundIcon: { uri: "https://via.placeholder.com/210x210" },
    backgroundColor: "#FE9BB3",
    lessons: lessons,
  },
  {
    id: "4",
    category: "English",
    name: "Chapter 2: Nelson Mandela Long Walk to Freedom",
    author: "Jack Smith",
    thumbnail: { uri: "https://via.placeholder.com/270x270" },
    image: { uri: "https://via.placeholder.com/690x360" },
    icon: { uri: "https://via.placeholder.com/600x600" },
    preview_240x240: {
      uri: "https://via.placeholder.com/240x240",
    },
    preview_330x330: {
      uri: "https://via.placeholder.com/330x330",
    },
    preview_480x288: {
      uri: "https://via.placeholder.com/480x288",
    },
    preview_1005x495: {
      uri: "https://via.placeholder.com/1005x495",
    },
    location: "London Universiry",
    instructor: "Elizabeth Parker",
    instructorPhoto: { uri: "https://via.placeholder.com/273x273" },
    instructorRating: "4.5",
    instructorReviews: "116",
    instructorStudents: "936",
    instructorCourses: "12",
    position: "Professional Software Developer and Educator",
    aboutTeacher:
      "I started working as a software developer at the age of 23, and never looked back. I explored careers as varied as being a  Game Developer, Educator and Drone Pilot, over the last 25 years. None of these provided a continual challenge in the same way the combination of...",
    duration: "5h  30m",
    price: "35.00",
    oldPrice: "55.00",
    rating: "5.0",
    ratings: "149",
    topRated: true,
    popular: true,
    isNew: true,
    speciallyForYou: true,
    ongoing: false,
    completed: true,
    wishlist: true,
    lectures: "23",
    backgroundIcon: { uri: "https://via.placeholder.com/210x210" },
    backgroundColor: "#ABC9FB",
    lessons: lessons,
  },
];

export { courses };
